
services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    volumes:
      - homeassistant-data:/config
      - /etc/localtime:/etc/localtime:ro

  semaphore:
    image: semaphoreui/semaphore
    container_name: semaphore
    restart: unless-stopped
    ports:
      - "3100:3000"
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=semaphore
      - SEMAPHORE_DB_HOST=semaphore-db
      - SEMAPHORE_DB_PORT=5432
      - SEMAPHORE_DB_DIALECT=postgres
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_ADMIN_PASSWORD=admin
    depends_on:
      - semaphore-db

  semaphore-db:
    image: postgres:13
    container_name: semaphore-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=semaphore
      - POSTGRES_PASSWORD=semaphore
      - POSTGRES_DB=semaphore
    volumes:
      - semaphore-db-data:/var/lib/postgresql/data


volumes:
  grafana-data:
  homeassistant-data:
  semaphore-db-data:

