
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    volumes:
      - homeassistant-data:/config
      - /etc/localtime:/etc/localtime:ro
  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml


  semaphore:
      ports:
          - 3100:3000
      image: semaphoreui/semaphore:v2.13.1
      environment:
          SEMAPHORE_DB_DIALECT: bolt
          SEMAPHORE_ADMIN: admin
          SEMAPHORE_ADMIN_PASSWORD: admin
          SEMAPHORE_ADMIN_NAME: admin
          SEMAPHORE_ADMIN_EMAIL: admin@localhost
          SEMAPHORE_SLACK_ALERT: "True"
      volumes:
          - semaphore_data:/var/lib/semaphore
          - semaphore_config:/etc/semaphore
          - semaphore_tmp:/tmp/semaphore



  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  grafana-data:
  homeassistant-data:
  #semaphore-db-data:
  prometheus-data:
  semaphore_data:
  semaphore_config:
  semaphore_tmp: