
services:
  grafana:
    # Platforma do wizualizacji danych monitorowania
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Hasło admina (zmień w produkcji)
      - GF_USERS_ALLOW_SIGN_UP=false     # Wyłączenie rejestracji użytkowników

  homeassistant:
    # System automatyki domowej
    image: homeassistant/home-assistant
    container_name: homeassistant
    restart: unless-stopped
    privileged: true  # Wymagane dla dostępu do urządzeń
    ports:
      - "8123:8123"
    volumes:
      - homeassistant-data:/config
      - /etc/localtime:/etc/localtime:ro  # Synchronizacja czasu z hostem

  blackbox-exporter:
    # Monitor zewnętrznych usług HTTP/HTTPS/DNS/TCP/ICMP
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml

  semaphore:
    # Interfejs użytkownika dla Ansible
    ports:
      - 3100:3000
    image: semaphoreui/semaphore:v2.13.1
    environment:
      SEMAPHORE_DB_DIALECT: bolt          # Typ bazy danych
      SEMAPHORE_ADMIN: admin              # Nazwa użytkownika admin
      SEMAPHORE_ADMIN_PASSWORD: admin     # Hasło admina (zmień w produkcji)
      SEMAPHORE_ADMIN_NAME: admin         # Wyświetlana nazwa admina
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_SLACK_ALERT: "True"       # Powiadomienia Slack włączone
    volumes:
      - semaphore_data:/var/lib/semaphore
      - semaphore_config:/etc/semaphore
      - semaphore_tmp:/tmp/semaphore

  prometheus:
    # System monitorowania i baza danych szeregów czasowych
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

# Wolumeny do przechowywania trwałych danych
volumes:
  grafana-data:
  homeassistant-data:
  prometheus-data:
  semaphore_data:
  semaphore_config:
  semaphore_tmp: