---
- name: Sprawdzenie dostępności ICMP urządzeń
  hosts: localhost  # Uruchom na węźle kontrolnym Ansible
  gather_facts: no  # Pomijamy zbieranie faktów dla szybszego wykonania

  tasks:
    - name: Pinguj każde urządzenie z węzła kontrolnego
      command: ping -c 2 {{ item }}
      loop: "{{ groups['all'] }}"  # Iteracja przez wszystkie hosty w inwentarzu
      ignore_errors: yes  # Kontynuuj nawet jeśli niektóre pingi się nie powiodą
      changed_when: false  # Nie oznaczaj tego zadania jako "zmienione"
      delegate_to: localhost  # Wykonaj na lokalnym hoście