---
- name: Test połączenia Ansible z urządzeniami
  hosts: all  # Docelowo wszystkie hosty w inwentarzu (zmień na konkretną grupę jeśli potrzeba)
  gather_facts: no  # Pomijamy zbieranie faktów dla szybszego wykonania

  tasks:
    - name: Sprawdź czy urządzenia odpowiadają przez Ansible
      ansible.builtin.ping: